In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a 1D array of numbers from 0 to 9
arr = np.arange(10)

# Print: shape, size, dtype, number of dimensions
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dtype:", arr.dtype)
print("Dimensions:", arr.ndim)

Shape: (10,)
Size: 10
Dtype: int64
Dimensions: 1


In [3]:
# Create a 3x3 matrix of numbers 1 to 9
matrix = np.arange(1, 10).reshape(3, 3)

# Extract: first row, last column, center element (5)
print("First row:", matrix[0])
print("Last column:", matrix[:, -1])
print("Center:", matrix[1, 1])

First row: [1 2 3]
Last column: [3 6 9]
Center: 5


In [4]:
# Create two arrays: a = [1,2,3], b = [[1],[2],[3]]
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

# Add them (broadcasting) and print result
result = a + b
print(result)
print("Result shape:", result.shape)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
Result shape: (3, 3)


In [5]:
# Create array: [10, 25, 30, 45, 50, 65, 70, 85, 90, 100]
arr = np.array([10, 25, 30, 45, 50, 65, 70, 85, 90, 100])

# Select only elements > 50 and < 90
filtered = arr[(arr > 50) & (arr < 90)]
print(filtered)

[65 70 85]


In [6]:
# Create two 2x2 matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiply (not element-wise) and print
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [7]:
# Create a DataFrame of 5 students
data = {
    'Name': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Vikram'],
    'Age': [21, 22, 20, 23, 21],
    'Marks': [85, 92, 78, 95, 88],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Bangalore', 'Mumbai']
}
df = pd.DataFrame(data)
print(df)

     Name  Age  Marks       City
0   Rahul   21     85      Delhi
1   Priya   22     92     Mumbai
2    Amit   20     78      Delhi
3   Sneha   23     95  Bangalore
4  Vikram   21     88     Mumbai


In [8]:
# From above df, select students with Marks > 85
top_students = df[df['Marks'] > 85]

# Sort by Age descending
sorted_df = top_students.sort_values('Age', ascending=False)
print(sorted_df)

     Name  Age  Marks       City
3   Sneha   23     95  Bangalore
1   Priya   22     92     Mumbai
4  Vikram   21     88     Mumbai


In [9]:
# Group by City and find average Marks per city
city_avg = df.groupby('City')['Marks'].mean()
print(city_avg)

City
Bangalore    95.0
Delhi        81.5
Mumbai       90.0
Name: Marks, dtype: float64


In [10]:
# Create array with NaN values
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

# Find: count of NaN, mean ignoring NaN, fill NaN with 0
print("NaN count:", np.isnan(arr).sum())
print("Mean (ignore NaN):", np.nanmean(arr))
print("Filled:", np.nan_to_num(arr, nan=0))

NaN count: 2
Mean (ignore NaN): 3.25
Filled: [1. 2. 0. 4. 0. 6.]


In [11]:
# Create a 5x5 grayscale image (random pixels 0-255)
image = np.random.randint(0, 256, size=(5, 5))

# Normalize to 0-1 range
normalized = image / 255.0

# Print: original, normalized, min, max
print("Original:\n", image)
print("Normalized:\n", normalized)
print("Min:", normalized.min(), "Max:", normalized.max())

Original:
 [[ 46 192 181 208 195]
 [185   2  71 123  68]
 [ 82  98 173 174  59]
 [ 19 183 239 175 246]
 [185  35 217  11  27]]
Normalized:
 [[0.18039216 0.75294118 0.70980392 0.81568627 0.76470588]
 [0.7254902  0.00784314 0.27843137 0.48235294 0.26666667]
 [0.32156863 0.38431373 0.67843137 0.68235294 0.23137255]
 [0.0745098  0.71764706 0.9372549  0.68627451 0.96470588]
 [0.7254902  0.1372549  0.85098039 0.04313725 0.10588235]]
Min: 0.00784313725490196 Max: 0.9647058823529412
